name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  terraform-eks:
    name: Terraform EKS Apply
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      # 3️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
        working-directory: terraform

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: terraform
